# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import identyfire_pb2 as identyfire__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in identyfire_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """---- Definição dos Serviços ----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictImage = channel.unary_unary(
                '/identyfire.ModelService/PredictImage',
                request_serializer=identyfire__pb2.PredictRequest.SerializeToString,
                response_deserializer=identyfire__pb2.PredictResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """---- Definição dos Serviços ----
    """

    def PredictImage(self, request, context):
        """Chamado pela GUI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictImage': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictImage,
                    request_deserializer=identyfire__pb2.PredictRequest.FromString,
                    response_serializer=identyfire__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identyfire.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identyfire.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """---- Definição dos Serviços ----
    """

    @staticmethod
    def PredictImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identyfire.ModelService/PredictImage',
            identyfire__pb2.PredictRequest.SerializeToString,
            identyfire__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrainingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTrainingJob = channel.unary_unary(
                '/identyfire.TrainingService/SubmitTrainingJob',
                request_serializer=identyfire__pb2.TrainRequest.SerializeToString,
                response_deserializer=identyfire__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/identyfire.TrainingService/GetJobStatus',
                request_serializer=identyfire__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=identyfire__pb2.JobStatusResponse.FromString,
                _registered_method=True)


class TrainingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTrainingJob(self, request, context):
        """Chamado por um agente ou cliente de admin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTrainingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTrainingJob,
                    request_deserializer=identyfire__pb2.TrainRequest.FromString,
                    response_serializer=identyfire__pb2.JobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=identyfire__pb2.JobStatusRequest.FromString,
                    response_serializer=identyfire__pb2.JobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identyfire.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identyfire.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTrainingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identyfire.TrainingService/SubmitTrainingJob',
            identyfire__pb2.TrainRequest.SerializeToString,
            identyfire__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identyfire.TrainingService/GetJobStatus',
            identyfire__pb2.JobStatusRequest.SerializeToString,
            identyfire__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
