# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identyfire.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'identyfire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10identyfire.proto\x12\nidentyfire\"7\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x13\n\x0bimage_bytes\x18\x02 \x01(\x0c\"4\n\x0fPredictResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\"3\n\x0cTrainRequest\x12\x13\n\x0b\x64\x61taset_uri\x18\x01 \x01(\t\x12\x0e\n\x06\x65pochs\x18\x02 \x01(\x05\"\x1d\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x98\x01\n\x11JobStatusResponse\x12\x32\n\x05state\x18\x01 \x01(\x0e\x32#.identyfire.JobStatusResponse.State\x12\x11\n\tlogs_path\x18\x02 \x01(\t\"<\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x32W\n\x0cModelService\x12G\n\x0cPredictImage\x12\x1a.identyfire.PredictRequest\x1a\x1b.identyfire.PredictResponse2\xa6\x01\n\x0fTrainingService\x12\x46\n\x11SubmitTrainingJob\x12\x18.identyfire.TrainRequest\x1a\x17.identyfire.JobResponse\x12K\n\x0cGetJobStatus\x12\x1c.identyfire.JobStatusRequest\x1a\x1d.identyfire.JobStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identyfire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=32
  _globals['_PREDICTREQUEST']._serialized_end=87
  _globals['_PREDICTRESPONSE']._serialized_start=89
  _globals['_PREDICTRESPONSE']._serialized_end=141
  _globals['_TRAINREQUEST']._serialized_start=143
  _globals['_TRAINREQUEST']._serialized_end=194
  _globals['_JOBRESPONSE']._serialized_start=196
  _globals['_JOBRESPONSE']._serialized_end=225
  _globals['_JOBSTATUSREQUEST']._serialized_start=227
  _globals['_JOBSTATUSREQUEST']._serialized_end=261
  _globals['_JOBSTATUSRESPONSE']._serialized_start=264
  _globals['_JOBSTATUSRESPONSE']._serialized_end=416
  _globals['_JOBSTATUSRESPONSE_STATE']._serialized_start=356
  _globals['_JOBSTATUSRESPONSE_STATE']._serialized_end=416
  _globals['_MODELSERVICE']._serialized_start=418
  _globals['_MODELSERVICE']._serialized_end=505
  _globals['_TRAININGSERVICE']._serialized_start=508
  _globals['_TRAININGSERVICE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
